# Generated by Django 3.0.7 on 2022-03-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
    ]
